/* Generated By:JavaCC: Do not edit this line. MINISQLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MINISQLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 1;
  /** RegularExpression Id. */
  int OR = 2;
  /** RegularExpression Id. */
  int MQUOTE = 3;
  /** RegularExpression Id. */
  int SELECT = 4;
  /** RegularExpression Id. */
  int UPDATE = 5;
  /** RegularExpression Id. */
  int DELETE = 6;
  /** RegularExpression Id. */
  int INSERT = 7;
  /** RegularExpression Id. */
  int FROM = 8;
  /** RegularExpression Id. */
  int INTO = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int VALUES = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int FUNCION = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int LBRACE = 17;
  /** RegularExpression Id. */
  int RBRACE = 18;
  /** RegularExpression Id. */
  int LBRACKET = 19;
  /** RegularExpression Id. */
  int RBRACKET = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int DOT = 23;
  /** RegularExpression Id. */
  int BACKSLASH = 24;
  /** RegularExpression Id. */
  int DOUBLEPOINT = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 31;
  /** RegularExpression Id. */
  int LETTER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"|\"",
    "\"\\\'\"",
    "\"SELECT\"",
    "\"UPDATE\"",
    "\"DELETE\"",
    "\"INSERT\"",
    "\"FROM\"",
    "\"INTO\"",
    "\"WHERE\"",
    "\"VALUES\"",
    "\"SET\"",
    "\"funcion\"",
    "\"AND\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\":\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
